import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientThemeProvider from "../components/ClientThemeProvider";
import { AuthProvider } from "../components/AuthProvider";
import Header from "../components/Header";
import Footer from "../components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ClientThemeProvider>
            <Header />
            <main style={{ minHeight: "80vh", animation: "fadeIn 0.7s" }}>
              {children}
            </main>
            <Footer />
          </ClientThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
